package com.nexora.roadmap.mapper;

import com.nexora.roadmap.dto.request.CreateRoadmapRequest;
import com.nexora.roadmap.dto.request.UpdateRoadmapRequest;
import com.nexora.roadmap.dto.response.RoadmapResponse;
import com.nexora.roadmap.entity.DifficultyLevel;
import com.nexora.roadmap.entity.Roadmap;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class RoadmapMapperTest {

    private RoadmapMapper roadmapMapper;

    @BeforeEach
    void setUp() {
        roadmapMapper = new RoadmapMapper();
    }

    @Test
    void toResponse_ShouldMapAllFields_WhenEntityIsValid() {
        // Given
        UUID id = UUID.randomUUID();
        LocalDateTime now = LocalDateTime.now();
        Roadmap roadmap = Roadmap.builder()
                .title("Java Fundamentals")
                .description("Learn Java from scratch")
                .difficultyLevel(DifficultyLevel.BEGINNER)
                .estimatedWeeks(8)
                .build();
        roadmap.setId(id);
        roadmap.setCreatedAt(now);
        roadmap.setUpdatedAt(now);

        // When
        RoadmapResponse response = roadmapMapper.toResponse(roadmap);

        // Then
        assertThat(response).isNotNull();
        assertThat(response.getId()).isEqualTo(id);
        assertThat(response.getTitle()).isEqualTo("Java Fundamentals");
        assertThat(response.getDescription()).isEqualTo("Learn Java from scratch");
        assertThat(response.getDifficultyLevel()).isEqualTo(DifficultyLevel.BEGINNER);
        assertThat(response.getEstimatedWeeks()).isEqualTo(8);
        assertThat(response.getCreatedAt()).isEqualTo(now);
        assertThat(response.getUpdatedAt()).isEqualTo(now);
    }

    @Test
    void toResponse_ShouldReturnNull_WhenEntityIsNull() {
        // When
        RoadmapResponse response = roadmapMapper.toResponse(null);

        // Then
        assertThat(response).isNull();
    }

    @Test
    void toEntity_ShouldMapAllFields_WhenRequestIsValid() {
        // Given
        CreateRoadmapRequest request = CreateRoadmapRequest.builder()
                .title("Spring Boot Advanced")
                .description("Deep dive into Spring Boot microservices")
                .difficultyLevel(DifficultyLevel.ADVANCED)
                .estimatedWeeks(12)
                .build();

        // When
        Roadmap roadmap = roadmapMapper.toEntity(request);

        // Then
        assertThat(roadmap).isNotNull();
        assertThat(roadmap.getId()).isNull(); // Id should be generated by DB/JPA
        assertThat(roadmap.getTitle()).isEqualTo("Spring Boot Advanced");
        assertThat(roadmap.getDescription()).isEqualTo("Deep dive into Spring Boot microservices");
        assertThat(roadmap.getDifficultyLevel()).isEqualTo(DifficultyLevel.ADVANCED);
        assertThat(roadmap.getEstimatedWeeks()).isEqualTo(12);
        assertThat(roadmap.getCreatedAt()).isNull();
        assertThat(roadmap.getUpdatedAt()).isNull();
    }

    @Test
    void toEntity_ShouldReturnNull_WhenRequestIsNull() {
        // When
        Roadmap roadmap = roadmapMapper.toEntity(null);

        // Then
        assertThat(roadmap).isNull();
    }

    @Test
    void updateEntity_ShouldMergeFields_WhenRequestIsValid() {
        // Given
        Roadmap roadmap = Roadmap.builder()
                .title("Old Title")
                .description("Old Description")
                .difficultyLevel(DifficultyLevel.INTERMEDIATE)
                .estimatedWeeks(4)
                .build();

        UpdateRoadmapRequest request = UpdateRoadmapRequest.builder()
                .title("New Title")
                .description("New Description")
                .difficultyLevel(DifficultyLevel.ADVANCED)
                .estimatedWeeks(6)
                .build();

        // When
        roadmapMapper.updateEntity(request, roadmap);

        // Then
        assertThat(roadmap.getTitle()).isEqualTo("New Title");
        assertThat(roadmap.getDescription()).isEqualTo("New Description");
        assertThat(roadmap.getDifficultyLevel()).isEqualTo(DifficultyLevel.ADVANCED);
        assertThat(roadmap.getEstimatedWeeks()).isEqualTo(6);
    }

    @Test
    void updateEntity_ShouldDoNothing_WhenRequestOrEntityIsNull() {
        // Given
        Roadmap roadmap = Roadmap.builder()
                .title("Old Title")
                .build();

        // When
        roadmapMapper.updateEntity(null, roadmap);
        // Then (no change)
        assertThat(roadmap.getTitle()).isEqualTo("Old Title");

        // When
        roadmapMapper.updateEntity(UpdateRoadmapRequest.builder().title("New").build(), null);
        // Then (should not fail with NPE)
    }
}
